---
title: "Multivariate Batch Effects"
author: "j1c"
date: "09/21/2022"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
require(tidyverse)
require(grid)
require(dplyr)
require(ggridges)
require(multcomp)
require(gridExtra)
require(parallel)
require(survey)
require(latex2exp)
require(energy)
require(gtable)
require(ggplotify)
require(kableExtra)
require(scales)
require(ggh4x)
require(cowplot)
#source('./causal_investigation_helpers.R')
```

# Modality {.tabset}

## fMRI {.tabset}

```{r}
select <- dplyr::select
mutate <- dplyr::mutate
arrange = dplyr::arrange
results <- readRDS("./data/pdcorr_outputs_fMRI_AAL.rds")

continent <- c(IBATRT = "North America", Utah1 = "North America", IPCAS2 = "Asia",
    SWU1 = "Asia", UWM = "North America", XHCUMS = "Asia", SWU4 = "Asia", BNU2 = "Asia",
    IPCAS3 = "Asia", SWU3 = "Asia", IPCAS4 = "Asia", NYU2 = "North America", IPCAS1 = "Asia",
    IPCAS7 = "Asia", UPSM1 = "North America", IACAS1 = "Asia", IPCAS5 = "Asia", NYU1 = "North America",
    NYU2 = "North America", BNU1 = "Asia", MRN1 = "North America", BNU3 = "Asia",
    HNU1 = "Asia", SWU2 = "Asia", IPCAS8 = "Asia", JHNU = "Asia", IPCAS6 = "Asia",
    BMB1 = "Europe", NKI24tr645 = "North America", NKI24tr1400 = "North America",
    NKI24tr2500 = "North America")
results$Covariate$Continent <- continent[results$Covariate$Dataset]

dset.ord <- results$Covariate %>%
    filter(Method == "Raw") %>%
    select(Dataset, Continent, n, N) %>%
    distinct() %>%
    arrange(Continent, N) %>%
    mutate(id = row_number()) %>%
    mutate(Dataset.Newname = sub("_", "", Dataset))
```

### Exploratory

```{r, fig.height=12, fig.width=9}
get_scaled_densities <- function(x, bw = 1.58) {
    res <- density(x, bw = bw)
    return(
        data.frame(
            x = res$x, y = res$y/max(res$y) *
                length(x)
        )
    )
}
covar.reord <- results$Covar.Tbl %>%
    filter(!(Dataset %in% c("NKI24tr645", "NKI24tr1400"))) %>%
    mutate(Dataset = recode_factor(Dataset, NKI24tr2500 = "NKI24")) %>%
    mutate(
        Dataset = factor(
            Dataset, levels = (dset.ord %>%
                filter(!(Dataset %in% c("NKI24tr645", "NKI24tr1400"))) %>%
                mutate(Dataset = recode_factor(Dataset, NKI24tr2500 = "NKI24")))$Dataset,
            ordered = TRUE
        )
    ) %>%
    group_by(Subid, Dataset) %>%
    arrange(desc(Session)) %>%
    do(head(., 1))

plt <- (df <- covar.reord %>%
    group_by(Dataset, Sex, Continent) %>%
    do(get_scaled_densities(.$Age)) %>%
    ungroup() %>%
    mutate(
        y = y/max(y) +
            as.numeric(Dataset)
    )) %>%
    ggplot(
        aes(
            ymin = as.numeric(Dataset),
            group = paste0(Dataset, Sex),
            color = factor(Sex),
            fill = factor(Sex),
            x = x, y = y, ymax = y
        )
    ) +
    geom_ribbon(alpha = 0.2) +
    geom_line(color = "black") +
    geom_jitter(
        data = covar.reord, aes(
            x = Age, y = as.numeric(Dataset),
            color = factor(Sex)
        ),
        width = 0.25, height = 0.2, size = 0.1, inherit.aes = FALSE
    ) +
    scale_fill_manual(
        values = c(`1` = "red", `2` = "blue"),
        labels = c(`1` = "Female", `2` = "Male"),
        name = "Sex"
    ) +
    scale_color_manual(
        values = c(`1` = "red", `2` = "blue"),
        labels = c(`1` = "Female", `2` = "Male"),
        name = "Sex", aesthetics = "color"
    ) +
    scale_y_continuous(
        breaks = 1:length(levels(df$Dataset)),
        labels = levels(df$Dataset),
        name = "Dataset", expand = c(0.02, 0.02),
        position = "right"
    ) +
    xlab("Age") +
    theme_bw(base_size = 20) +
    facet_grid("Continent~.", scales = "free_y", space = "free_y", switch = "y") +
    theme(panel.grid.minor = element_blank())

plt = plt %>%
    grid.arrange(left = ggpubr::text_grob("Continent", size = 25, rot = 90))

plt
```

```{r}


test <- read.csv("./data/composite_phenotypic_data.csv")
columns <- c("SITE_ID", "DX_GROUP", "SEX", "AGE_AT_SCAN", "Continent")

tdf <- test %>% select(columns) %>% mutate(SITE_ID = factor(SITE_ID, ordered = TRUE)) %>% mutate(Continent = factor(Continent)) %>% mutate(SEX = factor(SEX)) %>% mutate(DX_GROUP = factor(DX_GROUP)) %>% group_by(SITE_ID)

```

```{r,fig.height=12, fig.width=9}
get_scaled_densities <- function(x, bw = 1.58) {
    res <- density(x, bw = bw)
    return(
        data.frame(
            x = res$x, y = res$y/max(res$y) *
                length(x)
        )
    )
}

plt <- (df <- tdf %>%
    group_by(SITE_ID, SEX, Continent) %>%
    do(get_scaled_densities(.$AGE_AT_SCAN)) %>%
    ungroup() %>%
    mutate(
        y = y/max(y) +
            as.numeric(SITE_ID)
    )) %>%
    ggplot(
        aes(
            ymin = as.numeric(SITE_ID),
            group = paste0(SITE_ID, SEX),
            color = SEX, fill = SEX, x = x, y = y, ymax = y
        )
    ) +
    geom_ribbon(alpha = 0.2) +
    geom_line(color = "black") +
    geom_jitter(
        data = tdf, aes(
            x = AGE_AT_SCAN, y = as.numeric(SITE_ID),
            color = factor(SEX)
        ),
        width = 0.25, height = 0.2, size = 0.1, inherit.aes = FALSE
    ) +
    scale_fill_manual(
        values = c(`1` = "red", `2` = "blue"),
        labels = c(`1` = "Female", `2` = "Male"),
        name = "Sex"
    ) +
    scale_color_manual(
        values = c(`1` = "red", `2` = "blue"),
        labels = c(`1` = "Female", `2` = "Male"),
        name = "Sex", aesthetics = "color"
    ) +
    scale_y_continuous(
        breaks = 1:length(levels(df$SITE_ID)),
        labels = levels(df$SITE_ID),
        name = "Dataset", expand = c(0.02, 0.02),
        position = "right"
    ) +
    xlab("Age") +
    theme_bw(base_size = 20) +
    facet_grid(
        "Continent~.",
        scales = "free_y", space = "free_y", switch = "y"
    ) +
    theme(panel.grid.minor = element_blank())


plt = plt %>%
    grid.arrange(left = ggpubr::text_grob("Continent", size = 25, rot = 90))

plt


```


```{r}
```